micronaut:
  application:
    name: teste
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    url: jdbc:mysql://localhost:3306/demodb
    username: root
    password: toor
    driverClassName: com.mysql.cj.jdbc.Driver
    schema-generate: NONE
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
netty:
  default:
    allocator:
      max-order: 3
